### PR TITLE
Major clean up operation

### PR DESCRIPTION
**Pull request by hypeJunction**
I have pretty much rewritten the whole thing. 
New major feature is that users can choose to hide their public activity and membership listing from logged out users.
If you decide to merge, please add me to the authors and note that plugin upgrade has been sponsored by Bodyology Massage School Virtual Campus (http://bodyologymassagecourses.co.uk/forum)

### CODE REVIEW

**Comment by iionly** [comment]
It looks to me that "pretty much rewritten" is quite an understatement...

Please give me some time to look into your code to learn what it does (and how it does it!). I would also like to test if it works when using my Loginrequired plugin instead of the core walled-garden option.

And reason why you removed the friend_request plugin as suggested plugin from manifest.xml? For the friend access level to work as intended, the user whose profile page you want to see (or send a message to) must have made you a friend (not enough that you made him a friend). This is more easy to understand when all friend relationships are two-sided anyway as provided by the friend_request plugin.

**Comment by hypeJunction** [comment]
I didn't see any references to friend request or its code. It uses reverse friendship lookup.

I was pretty much lost in the code, so I have rewritten it for readability. It still uses all your logic, just simplifies all the settings checks.

**Comment by iionly** [comment]
Finally, I've some time to look into your PR to get a new release of the plugin out.

I'd been quite confused about the private/cache/retriever/catalog.xml file for a while as I didn't understand what it's supposed to do until I found out that it's something created by Netbeans. Safe to delete... right?

I want to make the release directly for Elgg 2.3. Almost done.

One problem I have is with the 'route', 'profile' routing that gives me a deprecation warning:

> WARNING: Deprecated in 2.3: 'route', 'profile' plugin hook should not be used to serve a response. Instead return an appropriate ResponseBuilder instance from an action or page handler. Do not terminate code execution with exit() or die() in Elgg\\PrivateProfiles\\Router::routeProfile

I've not been able to get it working using the 'route:rewrite', 'profile' plugin hook. With returning a "ResponseBuilder instance" it doesn't work at all. But switching to the 'route:rewrite', 'profile' plugin hook seems to work Is that okay or is there another approach that should be used now to fix the deprecation issue?

**Comment by hypeJunction** [comment]
Yes, sorry for the junk file. Normally NetBeans adds a gitignore entry but I guess there isn't a gitignore file. You can wipe it.
You can just return the array from route:rewrite hook, but move the hook handler registration outside of init handler. Maybe open a ticket for responsebuilder issue (elgg_ok_response() should be working as it's tested throughly).

**Pull request merged**
